#
# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 $(error You need to set GNUSTEP_MAKEFILES before compiling!)
endif

include $(GNUSTEP_MAKEFILES)/common.make

#
# SimpleTextEditor
#
VERSION = 1.0.0
PACKAGE_NAME = SimpleTextEditor
APP_NAME = SimpleTextEditor
SimpleTextEditor_APPLICATION_ICON = SimpleTextEditor.png

#
# Resource files
#
SimpleTextEditor_RESOURCE_FILES = SimpleTextEditorInfo.plist \
									Resources/gui.glade \
									Resources/SimpleTextEditor.png

#
# Class files
#
SimpleTextEditor_OBJC_FILES = Source/main.m Source/SimpleTextEditor.m Source/MultiDialog.m

OBJCFLAGS+= -I/usr/local/include/gtk-3.0 \
			-I/usr/local/include/glib-2.0 \
			-I/usr/local/lib/glib-2.0/include \
			-I/usr/local/include/pango-1.0 \
			-I/usr/local/include/harfbuzz \
			-I/usr/local/include/cairo \
			-I/usr/local/include/gdk-pixbuf-2.0 \
			-I/usr/local/include/atk-1.0 \
			-I/usr/local/GNUstep/Local/Library/Frameworks/CoreGTK.framework/Headers 

LDFLAGS=-lgtk-3 -lglib-2.0 -lCoreGTK
#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
